// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rqwrraiexdwhhkxwzedo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJxd3JyYWlleGR3aGhreHd6ZWRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1NDg1OTAsImV4cCI6MjA3MjEyNDU5MH0.ysSuZZqLdaMhB_t9CVwwIO0Nq6L3v6g2KkAy3YsWtVc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});